# name: Check
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   avoid_redundancy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Cancel Previous Runs
#         uses: styfle/cancel-workflow-action@0.9.1
#         with:
#           access_token: ${{ github.token }}
#   install:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 'lts'
#           check-latest: true
#       - name: Install Dependencies
#         run: npm ci
#       - name: Cache node_modules
#         uses: actions/upload-artifact@v4
#         with:
#           name: node_modules
#           path: node_modules

#   lint:
#     needs: [install]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#             node-version: 'lts'
#             check-latest: true
#       - name: Download node_modules
#         uses: actions/download-artifact@v4
#         with:
#           name: node_modules
#           path: node_modules
#       - name: Lint
#         run: npm run lint
#   build:
#     needs: [install]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 'lts'
#           check-latest: true
#       - name: Download node_modules
#         uses: actions/download-artifact@v4
#         with:
#           name: node_modules
#           path: node_modules
#       - name: Build
#         run: npm run build
#       - name: Cache build
#         uses: actions/upload-artifact@v4
#         with:
#           name: '.next'
#           path: '.next'
#           overwrite: true
#       - name: Cache node_modules
#         uses: actions/upload-artifact@v4
#         with:
#           name: node_modules
#           path: node_modules
#           overwrite: true
#   test:
#     needs: [build, lint, install]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts
#           check-latest: true
#       - name: Download node_modules
#         uses: actions/download-artifact@v4
#         with:
#           name: node_modules
#           path: node_modules
#       - name: Download build
#         uses: actions/download-artifact@v4
#         with:
#           name: '.next'
#           path: '.next'
#       - name: Test
#         run: npm start
