name: Feature Request
description: File a feature request
title: "[Feat]: "
labels: ["enhancement"]
projects: []
assignees:
  - eliyya
  - AngelesTeaa
body:
  - type: textarea
    id: "describe-the-feat"
    attributes:
      label: "Describe the feature"
      description: "A clear and concise description of what the feature you want to be added."
      placeholder: Tell us what you want to see.
    validations:
      required: true