import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import type { ReactNode } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'GreenTea',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`bg-[#578B5F] flex flex-col min-h-screen ${inter.className}`}>{children}</body>
        </html>
    )
}
