import { NavOptions, SystemNav } from '@/components/SystemNav'
import { getSessionPayload } from '@/lib/auth'
import { COOKIE } from '@/lib/constants'
import { getLikeRole } from '@/lib/roles'
import { Role } from '@prisma/client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import type { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })
const OPTIONS: {
    [key in Role]: NavOptions[]
} = {
    [Role.MASTER]: [],
    [Role.ADMIN]: [],
    [Role.PROMOTER]: [],
    [Role.SELLER]: [],
}

export const metadata: Metadata = {
    title: 'GreenTea System',
    description: 'Generated by create next app',
}

export default async function SystemLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const {payload} = await getSessionPayload(cookies().get(COOKIE.SESSION)?.value??'').catch(() => ({payload: null}))
    const like = getLikeRole(payload?.role??Role.SELLER, cookies().get(COOKIE.ADMIN_LIKE)?.value??'')

    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <SystemNav
                    options={OPTIONS[like].concat([
                        {name:'Dashboard',link:'/system'}
                    ])}
                />
                {children}
            </body>
        </html>
    )
}
