import { NavOptions, SystemNav } from '@/components/SystemNav'
import { getLikeRole, getSessionPayload } from '@/lib/auth'
import { COOKIE } from '@/lib/constants'
import { Role } from '@prisma/client'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })
const OPTIONS: {
    [key in Role]: NavOptions[]
} = {
    [Role.MASTER]: [
        { name: 'Create Cinema', link: '/system/new/cinema' },
        { name: 'Register Admin', link: '/system/new/admin' },
    ],
    [Role.ADMIN]: [
        { name: 'Register Employee', link: '/system/new/employee' },
    ],
    [Role.PROMOTER]: [],
    [Role.SELLER]: [],
}

export const metadata: Metadata = {
    title: 'GreenTea System',
    description: 'Generated by create next app',
}

export default async function SystemLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const { payload } = await getSessionPayload(
        cookies().get(COOKIE.SESSION)?.value ?? ''
    ).catch(() => ({ payload: null }))
    const like = getLikeRole(
        payload?.role ?? Role.SELLER,
        cookies().get(COOKIE.ADMIN_LIKE)?.value ?? ''
    )

    return (
        <>
            <SystemNav
                options={[
                    { name: 'Dashboard', link: '/system' },
                    ...OPTIONS[like]
                ]}
            />
            {children}
        </>
    )
}
